export const F1_TRACKS_2025 = [
    "Albert Park Circuit (Australia)",
    "Shanghai International Circuit (China)",
    "Suzuka International Racing Course (Japan)",
    "Bahrain International Circuit (Bahrain)",
    "Jeddah Corniche Circuit (Saudi Arabia)",
    "Miami International Autodrome (USA)",
    "Autodromo Enzo e Dino Ferrari (Imola)",
    "Circuit de Monaco (Monaco)",
    "Circuit de Barcelona-Catalunya (Spain)",
    "Circuit Gilles Villeneuve (Canada)",
    "Red Bull Ring (Austria)",
    "Silverstone Circuit (Great Britain)",
    "Circuit de Spa-Francorchamps (Belgium)",
    "Hungaroring (Hungary)",
    "Zandvoort (Netherlands)",
    "Autodromo Nazionale Monza (Italy)",
    "Baku City Circuit (Azerbaijan)",
    "Marina Bay Street Circuit (Singapore)",
    "Circuit of the Americas (USA)",
    "Autodromo Hermanos Rodriguez (Mexico)",
    "Interlagos (Brazil)",
    "Las Vegas Strip Circuit (USA)",
    "Lusail International Circuit (Qatar)",
    "Yas Marina Circuit (Abu Dhabi)"
];
